option(ASKOMPU_PORTABLE_WINDOWS "Rakenna Windowsin siirrettävä julkaisupaketti" ${WIN32})
if(WIN32 AND ASKOMPU_PORTABLE_WINDOWS)
  if(NOT MSVC OR NOT CMAKE_SIZEOF_VOID_P EQUAL 8 OR NOT ASKOMPU_STATIC_MSVC_RUNTIME OR ASKOMPU_USE_SYSTEM_SDL)
    message(FATAL_ERROR "Windows-julkaisupaketti tarvitsee x64-MSVC:n, staattisen ajonaikaiskirjaston ja haetun SDL:n")
  endif()
  set(runtime_destination ".")
  set(data_destination ".")
  set(license_destination "LISENSSIT")
  set(CPACK_GENERATOR ZIP)
  set(CPACK_PACKAGE_FILE_NAME "ASkompu-simulaattori-windows-x64")
  # CMake käyttää samaan MSVC-asennukseen kuuluvaa dumpbiniä DLL-auditissa.
  get_filename_component(msvc_bin "${CMAKE_LINKER}" DIRECTORY)
  find_program(ASKOMPU_DUMPBIN dumpbin HINTS "${msvc_bin}" REQUIRED)
  configure_file("${CMAKE_CURRENT_LIST_DIR}/VerifyWindowsRuntime.cmake.in"
    "${CMAKE_CURRENT_BINARY_DIR}/VerifyWindowsRuntime.cmake" @ONLY)
else()
  set(runtime_destination bin)
  set(data_destination share/askompu-simulaattori)
  set(license_destination "${data_destination}/LISENSSIT")
  set(CPACK_GENERATOR TGZ)
  set(CPACK_PACKAGE_FILE_NAME "ASkompu-simulaattori-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
endif()
install(TARGETS askompu-simulaattori RUNTIME DESTINATION "${runtime_destination}" COMPONENT Runtime)
if(WIN32 AND ASKOMPU_PORTABLE_WINDOWS)
  install(SCRIPT "${CMAKE_CURRENT_BINARY_DIR}/VerifyWindowsRuntime.cmake" COMPONENT Runtime)
  install(FILES release/README-windows.txt DESTINATION . RENAME README.txt COMPONENT Runtime)
else()
  install(FILES README.md DESTINATION "${data_destination}" COMPONENT Runtime)
endif()
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/generated/BUILDINFO-$<CONFIG>.txt"
  DESTINATION "${data_destination}" RENAME BUILDINFO.txt COMPONENT Runtime)
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/simulator-source.zip"
  DESTINATION "${data_destination}" COMPONENT Runtime)
install(FILES tools/core_versions.py DESTINATION "${data_destination}/tools" COMPONENT Runtime)
install(FILES "${ASKOMPU_CORE_ROOT}/LICENSE" DESTINATION "${license_destination}" RENAME ASkompu-LICENSE.txt COMPONENT Runtime)
install(FILES "${imgui_SOURCE_DIR}/LICENSE.txt" DESTINATION "${license_destination}" RENAME ImGui-LICENSE.txt COMPONENT Runtime)
install(FILES assets/Roboto-LICENSE.txt THIRD_PARTY.md DESTINATION "${license_destination}" COMPONENT Runtime)
if(NOT ASKOMPU_USE_SYSTEM_SDL)
  install(FILES "${sdl_SOURCE_DIR}/LICENSE.txt" DESTINATION "${license_destination}" RENAME SDL-LICENSE.txt COMPONENT Runtime)
endif()
set(CPACK_PACKAGE_NAME ASkompu-simulaattori)
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_VENDOR "ASkompu-simulaattori")
set(CPACK_PACKAGE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/packages")
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY OFF)
set(CPACK_PACKAGING_INSTALL_PREFIX "/ASkompu-simulaattori")
set(CPACK_COMPONENTS_ALL Runtime)
include(CPack)
